name: QuickPOS CI

on:
  push:
    branches:
      - feature/**
      - bugfix/**

  pull_request:
    branches:
      - main

jobs:

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Syntax Check
        run: find . -name "*.php" -exec php -l {} \;

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests

  commit-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Commit Message
        run: |
          git log --format=%B -n 1 | grep -E '\[POS-[0-9]+\]'
